### ISSUE TITLE
Installs an unstripped executable

### ISSUE THREAD

**Issue by yurivict** [pi-kvm/ustreamer#6]
```
====> Running Q/A tests (stage-qa)
Warning: 'bin/ustreamer' is not stripped consider trying INSTALL_TARGET=install-strip or using ${STRIP_CMD}
```

Please strip it!

**Comment by mdevaev** [comment]
Umm, what is that? It's a FreeBSD package?

**Comment by yurivict** [comment]
yes

**Comment by mdevaev** [comment]
I've added make targets `install-strip` (and `uninstall` also but who cares) following this doc: https://www.gnu.org/prep/standards/html_node/Standard-Targets.html
That's what you need?

**Comment by mdevaev** [comment]
Wait wat? Ustreamer working under FreeBSD? But how? I thought it's not portable because I used Linux-specific APIs.

**Comment by yurivict** [comment]
> UPD: This is it? https://www.freshports.org/multimedia/ustreamer

Yes, it build on FreeBSD.

> I can add this link to readme.

Please do. Thank you!

**Comment by mdevaev** [comment]
Done! Bumped to 0.75

**Comment by yurivict** [comment]
Thanks!
